require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'

# Style preferences
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 22
  Exclude:
    - 'spec/**/*'
    - 'lib/langfuse/exporter.rb'

Metrics/AbcSize:
  Max: 21
  Exclude:
    - 'lib/langfuse/exporter.rb'

Metrics/ClassLength:
  Max: 140

Metrics/ParameterLists:
  Max: 6

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#'  # Allow long comments

# RSpec
RSpec/ExampleLength:
  Max: 32

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/DescribeClass:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

# Capybara - disable to avoid cop bugs
Capybara/RSpec/PredicateMatcher:
  Enabled: false

# Lint
Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*'

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/langfuse/exporter.rb'  # OpenTelemetry interface methods
